#!/bin/bash

# Check if a topic is provided
if [ -z "$1" ]; then
  echo "Usage: $0 \"<topic>\""
  exit 1
fi

TOPIC="$1"
SLUGIFIED_TOPIC=$(echo "$TOPIC" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)
OUTPUT_FILE="docs/${SLUGIFIED_TOPIC}.md"

# Define the prompt for the Gemini CLI
PROMPT="You are an expert author. Write a comprehensive book chapter on the topic of '${TOPIC}'. The chapter should be well-structured, informative, and engaging. The output should be in Markdown format, ready to be included in a Docusaurus website."

# Placeholder for the actual Gemini CLI command
# This command will need to be replaced with the correct one for your setup.
echo "Generating chapter for topic: ${TOPIC}..."
# gemini-cli --prompt "$PROMPT" > "book-project/${OUTPUT_FILE}"

# For now, create a dummy file
echo "# ${TOPIC}" > "book-project/${OUTPUT_FILE}"
echo "" >> "book-project/${OUTPUT_FILE}"
echo "This is a placeholder for the chapter on ${TOPIC}." >> "book-project/${OUTPUT_FILE}"
echo "The real content will be generated by the Gemini CLI." >> "book-project/${OUTPUT_FILE}"


echo "Chapter generated at: book-project/${OUTPUT_FILE}"
